.TH vramsteg 1 2010-06-06 "vramsteg 1.0.0" "User Manuals"

.SH NAME
vramsteg \- building blocks for UI

.SH SYNOPSIS
.B vramsteg
('progress' in Swedish) is a ...

.SH DESCRIPTION

.SH EXAMPLES

.SH FILES

.SH "CREDITS & COPYRIGHTS"
Vramsteg was written by P. Beckingham <paul@beckingham.net>
and F. Hernandez <ultrafedde@gmail.com>.

.br
Copyright (C) 2010 P. Beckingham, F. Hernandez.

Vramsteg is distributed under the GNU General Public License.  See
http://www.gnu.org/licenses/gpl-2.0.txt for more information.

.SH SEE ALSO
For more information regarding vramsteg, the following may be referenced:

.TP
The official site at
<http://vitapi.org>

.TP
The official code repository at
<git://tasktools.org/vramsteg.git/>

.TP
You can contact the project by writing an email to
<support@vitapi.org>

.SH REPORTING BUGS
.TP
Bugs in vramsteg may be reported to <support@vitapi.org>

