#! /bin/bash

echo Default style
echo Default colors
echo With width
echo With percentage
echo With elapsed time
echo With estimated remaining time
echo With label
echo With remove

START=$(../vramsteg --now)
for i in 0 1 2 3 4 5 6 7 8 9 10
do
  ../vramsteg --width=80 --label=label --min=0 --max=10 --current=$i --percentage --elapsed --estimate --start $START
  sleep 1
done

../vramsteg --width=80 --label=label --min=1 --max=10 --current=10 --percentage --elapsed --estimate --start $START --remove

