#! /bin/bash

echo Default style
echo Default colors
echo Default width
echo No percentage
echo No elapsed time
echo No estimated remaining time
echo With label
echo No remove

for i in 0 1 2 3 4 5 6 7 8 9 10
do
  ../vramsteg --label="Bar label" --min=0 --max=10 --current=$i
  sleep 1
done
echo

