#! /bin/bash

../vramsteg --style mono --min 0 --max 3 --current 0
sleep 1
../vramsteg --style mono --min 0 --max 3 --current 1
sleep 1
../vramsteg --style mono --min 0 --max 3 --current 2
sleep 1
../vramsteg --style mono --min 0 --max 3 --current 3
sleep 1
../vramsteg --remove
echo

